function NFLCombineAndProDayData_1987_2021_ = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NFLCOMBINEANDPRODAYDATA_1987_2021_ = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  NFLCOMBINEANDPRODAYDATA_1987_2021_ = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  NFLCombineAndProDayData_1987_2021_ = importfile("C:\Users\kajv1\OneDrive\Documents\GitHub\KAV_KINE6203_Class_Assignment_Solutions\assignment3\NFL Combine and pro day data (1987 - 2021).csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Sep-2026 12:41:40

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 13);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Year", "Name", "College", "POS", "Height_in_", "Weight_lbs_", "Wonderlic", "x40Yard", "BenchPress", "VertLeap_in_", "BroadJump_in_", "Shuttle", "x3Cone"];
opts.VariableTypes = ["double", "string", "categorical", "categorical", "double", "double", "string", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Name", "Wonderlic"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Name", "College", "POS", "Wonderlic"], "EmptyFieldRule", "auto");

% Import the data
NFLCombineAndProDayData_1987_2021_ = readtable(filename, opts);

end
